### PR TITLE
Read only fields expansion

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Referenced in #194. Shouldn't affect tests

#### What?

Temp fix for `$product->update()`. Really the API probably needs to change.
 
#### Tickets / Documentation

#194

### CODE REVIEW

**Comment by ICarpenter** [comment]
👍 This looks great @Lewiscowles1986, thank you!

**Comment by ICarpenter** [comment]
@lord2800 can we merge this puppy?

**Comment by lord2800** [comment]
I can't, but I agree that this looks great!

**Comment by Lewiscowles1986** [comment]
I may be annoying and close this, then re-submit from my organisation (as I'd like to introduce a failing test).

Thoughts?

**Comment by lord2800** [comment]
I'm OK with that.

**Pull request closed without merging**
