### PR TITLE
Ported Webhooks from #101

### PR DESCRIPTION
**Pull request by Lewiscowles1986**
Added webhooks with DocBlocks (needs tests really) based on #101 updated to get rid of merge conflicts

### CODE REVIEW

**Comment by snoogans235** [comment]
Just posted in 101 and was directed here.  What needs to be done to get this merged into master?

**Comment by Lewiscowles1986** [comment]
No clue but TBH lot of fuss

**Comment by philipmuir** [comment]
will chase it up today

**Comment by snoogans235** [comment]
Sounds good.  If there is something that needs to be done, I'll be here.

**Comment by Lewiscowles1986** [comment]
Aww pants lol. Now I'll have to re-PR the tests :rofl:

**Pull request merged**
