### PR TITLE
API-94 - adding else case to switch back to JSON mode if useXml is false

### PR DESCRIPTION
**Pull request by bc-bfenton**
## What
Else case to switch content type and "use raw" back to JSON-based settings.

## Why
Inability to turn this off was hindering functional testing.

### CODE REVIEW

**Comment by bc-bfenton** [comment]
@zvuki @bc-joshroe @ICarpenter

**Comment by lord2800** [comment]
:+1:

**Comment by ICarpenter** [comment]
:+1:

**Comment by bc-sandeep** [comment]
tested this fix locally along with @bc-joshroe :green_heart: for xml tests it fixed

**Pull request merged**
